version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./front:/front
      - yosan-node_modules:/front/node_modules
    tty: true

volumes:
  yosan-node_modules: